[package]
name = "pane"
version = "0.0.0"
edition = "2024"
homepage = "https://github.com/mthierman/pane-rs"
repository = "https://github.com/mthierman/pane-rs.git"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
windows = { workspace = true }
